<?php
$helper = $this->helper('ls_cashpresso');
$mode = $helper->getMode() ? 'live' : 'test';
$debugMode = $helper->isDebugEnabled();
?>

<ul class="form-list checkout-agreements" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <?php if ($this->getInstructions()): ?>
    <li>
        <div class="<?php echo $this->getMethodCode() ?>-instructions-content agreement-content">
            <?php echo nl2br($this->getInstructions()) ?>
        </div>
    </li>
    <?php endif; ?>
    <li>
        <input type="hidden" id="cashpressoToken" name="cashpressoToken">

        <div id="cashpresso-checkout"></div>

        <?php /* <div id = "cashpresso-availability-banner"></div> */ ?>
    </li>
</ul>

<script type="text/javascript">
    //<![CDATA[
    if (window.C2EcomCheckout) {
        window.C2EcomCheckout.refresh();
        <?php if ($debugMode && ($mode=='test')): ?>
        console.log('<?php echo $this->refreshOptionalData() ?>');
        <?php endif; ?>
        <?php echo $this->refreshOptionalData() ?>
    }
    //]]>
</script>