<?php
/**
 * 08.03.18
 * LimeSoda - dockerized-magento (Cashpresso)
 *
 * Created by Anton Sannikov.
 *
 * @category    Lime_Soda
 * @package     dockerized-magento (Cashpresso)
 * @copyright   Copyright (c) 2018 LimeSoda. (http://www.limesoda.com)
 *
 * @file Active.php
 */

class LimeSoda_Cashpresso_Model_Adminhtml_System_Config_Backend_Active extends Mage_Core_Model_Config_Data
{
    protected function _beforeSave()
    {
        echo '<pre><br/>';
        var_dump($this->getValue());
        die();
        return parent::_beforeSave(); // TODO: Change the autogenerated stub
    }
}