<?php
/**
 * 22.02.18
 * LimeSoda - cashpresso
 *
 * Created by Anton Sannikov.
 *
 * @category    Limesoda_Cashpresso
 * @package     cashpresso
 * @copyright   Copyright (c) 2018 LimeSoda. (http://www.limesoda.com)
 *
 * @file app/design/frontend/base/default/template/limesoda/cashpreso/page/js/head.phtml
 */
?>
<?php $helper = $this->helper('ls_cashpresso'); ?>
<?php $isProductPage = $helper->isProductPage(); ?>
<?php $url = $helper->getCheckoutUrl(); ?>
<?php $checkoutRedirect = Mage::helper('checkout/cart')->getShouldRedirectToCart() ?>

<script type="text/javascript">

    var LS_CP_COOKIE_NAME = 'ls_cs_add_product_redirection';

    CPCookie = Class.create();
    CPCookie.prototype = {
        set: function (name, value, days) {
            var expires = "";
            if (days) {
                var date = new Date();
                date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
                expires = "; expires=" + date.toUTCString();
            }
            document.cookie = name + "=" + (value || "") + expires + "; path=/";
        },
        get: function (name) {
            var nameEQ = name + "=";
            var ca = document.cookie.split(';');
            for (var i = 0; i < ca.length; i++) {
                var c = ca[i];
                while (c.charAt(0) == ' ') c = c.substring(1, c.length);
                if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length, c.length);
            }
            return null;
        },
        delete: function (name) {
            document.cookie = name + '=; Max-Age=-99999999;';
        }
    }

    var LSCPCookie = new CPCookie();
    <?php if ($isProductPage): ?>
    if (LSCPCookie.get(LS_CP_COOKIE_NAME)){
        LSCPCookie.delete(LS_CP_COOKIE_NAME);
        window.location.href = '<?php echo $url ?>';
    }
    <?php endif; ?>

    function c2Checkout() {
        <?php if (!$checkoutRedirect): ?>
        LSCPCookie.set(LS_CP_COOKIE_NAME, 1, 1);
        <?php endif; ?>
        productAddToCartForm.submit(this);
    }
</script>